# hash:sha256:b2ecddae209bd5c18a5d0f41cdf3e82d6c8d35c38bf47ee6eb5dbf80b7e4c5de
ARG REGISTRY_HOST
FROM $REGISTRY_HOST/codeocean/jupyterlab:3.6.1-miniconda4.12.0-python3.9-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive
ARG GIT_ASKPASS
COPY git-askpass /
